language: go

before_install:
   - sudo apt-get update -qq
   - sudo apt-get install python-dev -qq

install:
  - mkdir -p $GOPATH/src/github.com/sbinet/go-python
  - mv * $GOPATH/src/github.com/sbinet/go-python
  - pushd $GOPATH/src/github.com/sbinet/go-python
  - make

notifications:
  email:
    recipients:
      - binet@cern.ch
    on_success: change
    on_failure: always
