language: go

before_install:
   - sudo apt-get update -qq
   - sudo apt-get install python-dev -qq

install:
  - go get -x -v github.com/sbinet/go-python

notifications:
  email:
    recipients:
      - binet@cern.ch
    on_success: change
    on_failure: always
